id: A2A24A462
title: 'Nectar Shower of Blessings: A Song of Yearning Devotion Recalling the Everpresent
  Gurus'
type: translation
pechas:
- I0C1496EA
- I376C5CA6
- I5F3FFB03
- I7116F5CC
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:48:23.991453
  last_modified_at: 2023-01-04 12:48:23.991473
  collections:
  - Khandro Tsering Chödrön Series
  - Works of Tibetan Masters
alignment_to_base:
  I0C1496EA/C43A: 2F32
  I376C5CA6/B693: 2F32
  I5F3FFB03/8CD8: 2F32
  I7116F5CC/8A79: 2F32
